spring.application.name=distribution-centre-api

server.port=8080

spring.datasource.url=jdbc:h2:mem:centres
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.web.cors.allowed-origins=http://localhost:8081